@server = http://localhost:3000

###GET 요청 전송
GET {{server}}/person

### POST 요청 전송
POST {{server}}/person
Content-Type: application/json

{
    "name": "TEST",
    "age": 30,
    "email": "test@gmail.com"
}

### 생성 문서 확인
GET {{server}}/person/test@gmail.com 

### 문서 수정
PUT {{server}}/person/test@gmail.com
Content-Type: application/json

{
    "age": 32
}

### 문서 삭제
DELETE {{server}}/person/test@gmail.com